class DataFrameTokens():
    GT_ANNOT_SUFFIX = '_gt'
    LABELS_GROUP_KEY = 'frame_id'
    END_EVENT_TOKEN = 'end_frame'
    VIDEO_TOKEN = 'video'
    IMAGE_FILE_PRED_TOKEN = 'image_file_name_pred'
    IMAGE_FILE_ANNOTATION_TOKEN = 'image_file_name_annotation'
    IMAGE_FILE_DATA_TOKEN = 'image_file_name_data'
    UNIQUE_BATCH_TOKEN = 'batch_unique_id'
    HAS_VALUE_TOKEN = 'has_value'
    BB_X = 'x'
    BB_Y = 'y'
    BB_WIDTH = 'width'
    BB_HEIGHT = 'height'